[package]
name = "lead-w"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lead = { path = "../lead" }
lead-vm = { path = "../lead-vm" }
leadc = { path = "../leadc" }
wasm-bindgen = "0.2.92"
